name: Generate File List

on:
  push:
    paths:
      - 'assets/files/**'    # adjust path
      - '.github/workflows/generate-file-list.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        id: list_files
        run: |
          echo "listing files in assets/files/"
          files=$(find assets/files/ -type f | awk '{print "- name: \"" $0 "\"\n  path: \"/" $0 "\""}')
          # wrap in YAML
          printf "%s\n" "$files" > _data/files.yml

      - name: Commit updated file list
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update file list"
          file_pattern: "_data/files.yml"
          branch: ${{ github.ref_name }}
